# fly.toml app configuration file generated for mini-message-board-pug on 2023-07-31T16:29:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mini-message-board-pug"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
